### ISSUE TITLE
视频，音频组件无法正常使用

### ISSUE THREAD

**Issue by Misaka-L** [laiyuzenb/kook_message_preview#3]
## 问题描述

视频，音频组件部分正常渲染。但是视频组件无预览图。且所有组件都无法播放。

已排除网络问题，即使是本地文件（直接放到开发环境目录里）也不行。DevTools 没有发现网络错误

![image](https://github.com/laiyuzenb/kook_message_preview/assets/42287372/4bb7050d-469f-4ba0-a6e0-8561f80922bc)

**Comment by FeClickEngineer** [comment]
我明天看下

**Comment by FeClickEngineer** [comment]
音频播放可以解决，视频波放暂时不方便处理，原本视频播放逻辑是放在 kook app内作的创建预览窗口，并没有放在组件内处理

**Comment by FeClickEngineer** [comment]
音频播放已解决 视频播放暂不方便支持
