### ISSUE TITLE
TypeScript 支持

### ISSUE THREAD

**Issue by modcrafts** [laiyuzenb/kook_message_preview#4]
是否可以添加完整的 TS 类型支持?

**Comment by FeClickEngineer** [comment]
只有四个参数 你还要什么其他的类型提示么？
后续我抽空补下 d.ts文件好了

**Comment by Misaka-L** [comment]
如果 #11 被合并了.... 那可能就真的很需要 ts 提示了
不过卡片消息的 ts 提示会比较麻烦

**Comment by FeClickEngineer** [comment]
https://github.com/kaiheila/kook_message_preview/pull/1 已经好了
