### ISSUE TITLE
支持注入上下文信息

### ISSUE THREAD

**Issue by Misaka-L** [laiyuzenb/kook_message_preview#6]
支持注入上下文（如用户，频道等，而不是碰到 mention 全部都是 #频道 和 ID）

**Comment by FeClickEngineer** [comment]
这个你是想传入好友列表 频道列表 还是 传入 renderUser 和 renderChannel 回调函数

**Comment by Misaka-L** [comment]
> 这个你是想传入好友列表 频道列表 还是 传入 renderUser 和 renderChannel 回调函数

传入 renderUser 和 renderChannel 会相对来说自定义程度高一点

**Comment by FeClickEngineer** [comment]
> > 这个你想传入好友列表频道列表还是传入 renderUser 和 renderChannel 回调函数
> 
> 启动 renderUser 和 renderChannel 相对来说自定义程度高一点

本周内提供
